-- Run this in your Supabase SQL Editor

-- 1. SETUP LEADS TABLE
create table if not exists public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    type text, -- e.g., 'calculator', 'chat'
    name text,
    email text,
    phone text,
    status text default 'new',
    user_data jsonb default '{}'::jsonb, -- Stores calculator results
    session_id text
);

-- Ensure 'user_data' column exists (safe check)
do $$ 
begin
    if not exists (select 1 from information_schema.columns where table_name = 'leads' and column_name = 'user_data') then
        alter table public.leads add column user_data jsonb default '{}'::jsonb;
    end if;
end $$;


-- 2. SETUP STORAGE BUCKET ('evidence')
-- This creates a public bucket for photo uploads
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'evidence', 
    'evidence', 
    true, 
    5242880, -- 5MB Limit per file
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set public = true;


-- 3. STORAGE POLICIES (Allow Uploads)
-- WARNING: This allows public uploads. For production, add auth logic.
create policy "Public Upload Evidence"
on storage.objects for insert
with check ( bucket_id = 'evidence' );

create policy "Public View Evidence"
on storage.objects for select
using ( bucket_id = 'evidence' );
